# Font
font_family Terminess Nerd Font Mono
font_size 15

terminal.force_asterisks = true

map ctrl+plus change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0

# Colors
foreground #E4DED2
background #0A0A12

# Regular colors
color0 #1C1C28
color1 #C25B5B
color2 #8BAA82
color3 #E6C27A
color4 #6270A8
color5 #9A7398
color6 #95B3B0
color7 #2A2A38

# Bright colors
color8 #2A2A38
color9 #C25B5B
color10 #8BAA82
color11 #E6C27A
color12 #6270A8
color13 #9A7398
color14 #95B3B0
color15 #FFF8F2

# Background opacity
background_opacity 0.8

confirm_os_window_close 0
