
font=ShureTechMono Nerd Font:size=15
width=40
lines=20
terminal=kitty -e  # Command to run in terminal
prompt="> "
layer=overlay

[colors]
background=00000080
text=ffffffff
selection=ffffffff
selection-text=000000ff
border=000000ff
match=00ff9dff
selection-match=ff004cff

[border]
radius=0
width=5

[dmenu]
exit-immediately-if-empty=yes

[main]
layer=overlay
# Força o namespace para "fuzzel"
namespace=fuzzel

