
font=DepartureMono Nerd Font:size=20
width=50
lines=20
terminal=ghostty -e  # Command to run in terminal
prompt="> "
layer=overlay

[colors]
background=03191b80
text=ffffffff
selection=ffffffff
selection-text=000000ff
border=331800ff
match=00ff9dff
selection-match=ff004cff

[border]
radius=0
width=3

[dmenu]
exit-immediately-if-empty=yes

[main]
layer=overlay
# Força o namespace para "fuzzel"
namespace=fuzzel

