[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\b/home/hp)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\x33\0\0\x2\xee\0\0\x6\xb1\0\0\x5\x95\0\0\x3\x33\0\0\x2\xee\0\0\x6\xb1\0\0\x5\x95\0\0\0\0\0\0\0\0\rp\0\0\x3\x33\0\0\x2\xee\0\0\x6\xb1\0\0\x5\x95)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(895 608)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/hp/V%C3%ADdeos/Natureza%20Morta-Viva.mp4
times=144083
