directory: /run/user/1000/gvfs/smb-share:server=192.168.1.65,share=music
library: ~/.config/beets/musiclibrary.db
 
import:
  move: yes
  write: yes
  timid: no

plugins:
  - fetchart
  - embedart
  - lastgenre
  - scrub
 
paths:
  default: $albumartist/$album/$track - $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album/$track - $title
 
fetchart:
  auto: yes
 
embedart:
  auto: yes
