
preload=/home/hp/Pictures/Wallpapers/basic1.png
preload=/home/hp/Pictures/Wallpapers/Traveller.jpg

splash = false

wallpaper {
    monitor=DP-3
    path=~/Pictures/Wallpapers/arch.png
    fit_mode=cover
}

wallpaper {
    monitor=HEADLESS-2
    path=~/Pictures/Wallpapers/Traveller.jpg
    fit_mode=cover
}
