[General]
WindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\ro\0\0\x5\x9f\0\0\0\0\0\0\0\0\0\0\ro\0\0\x5\x9f\0\0\0\0\x2\0\0\0\rp\0\0\0\0\0\0\0\0\0\0\ro\0\0\x5\x9f)

[SessionTab]
splitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1\0\0\0\x1\0\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
topSplitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xdd\0\0\0\xc0\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)

[SystemTab]
splitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1\0\0\0\x1\0\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
topSplitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xdd\0\0\0\xc0\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
