music_directory     "~/.local/share/nicotine/downloads/"        # point this at your Nicotine+ download folder
playlist_directory  "~/.config/mpd/playlists"
db_file             "~/.config/mpd/database"
log_file            "~/.config/mpd/log"
pid_file            "~/.config/mpd/pid"
state_file          "~/.config/mpd/state"
sticker_file        "~/.config/mpd/sticker.sql"

bind_to_address     "localhost"

audio_output {
    type    "pipewire"   # or "pulse" if you use PulseAudio
    name    "My Output"
}
